/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppWithdrawRouteImport } from './routes/app/withdraw'
import { Route as AppTopupRouteImport } from './routes/app/topup'
import { Route as AppStatementRouteImport } from './routes/app/statement'
import { Route as AppSendRouteImport } from './routes/app/send'
import { Route as AppMerchantRouteImport } from './routes/app/merchant'
import { Route as AppLoansRouteImport } from './routes/app/loans'
import { Route as AppLipaRouteImport } from './routes/app/lipa'
import { Route as AppAirtimeRouteImport } from './routes/app/airtime'
import { Route as AppAgentRouteImport } from './routes/app/agent'
import { Route as AppAccountRouteImport } from './routes/app/account'
import { Route as ApiPublicMpesaStkCallbackRouteImport } from './routes/api/public/mpesa/stk-callback'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWithdrawRoute = AppWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AppRoute,
} as any)
const AppTopupRoute = AppTopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => AppRoute,
} as any)
const AppStatementRoute = AppStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => AppRoute,
} as any)
const AppSendRoute = AppSendRouteImport.update({
  id: '/send',
  path: '/send',
  getParentRoute: () => AppRoute,
} as any)
const AppMerchantRoute = AppMerchantRouteImport.update({
  id: '/merchant',
  path: '/merchant',
  getParentRoute: () => AppRoute,
} as any)
const AppLoansRoute = AppLoansRouteImport.update({
  id: '/loans',
  path: '/loans',
  getParentRoute: () => AppRoute,
} as any)
const AppLipaRoute = AppLipaRouteImport.update({
  id: '/lipa',
  path: '/lipa',
  getParentRoute: () => AppRoute,
} as any)
const AppAirtimeRoute = AppAirtimeRouteImport.update({
  id: '/airtime',
  path: '/airtime',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicMpesaStkCallbackRoute =
  ApiPublicMpesaStkCallbackRouteImport.update({
    id: '/api/public/mpesa/stk-callback',
    path: '/api/public/mpesa/stk-callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/account': typeof AppAccountRoute
  '/app/agent': typeof AppAgentRoute
  '/app/airtime': typeof AppAirtimeRoute
  '/app/lipa': typeof AppLipaRoute
  '/app/loans': typeof AppLoansRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/send': typeof AppSendRoute
  '/app/statement': typeof AppStatementRoute
  '/app/topup': typeof AppTopupRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/': typeof AppIndexRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/account': typeof AppAccountRoute
  '/app/agent': typeof AppAgentRoute
  '/app/airtime': typeof AppAirtimeRoute
  '/app/lipa': typeof AppLipaRoute
  '/app/loans': typeof AppLoansRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/send': typeof AppSendRoute
  '/app/statement': typeof AppStatementRoute
  '/app/topup': typeof AppTopupRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app': typeof AppIndexRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/account': typeof AppAccountRoute
  '/app/agent': typeof AppAgentRoute
  '/app/airtime': typeof AppAirtimeRoute
  '/app/lipa': typeof AppLipaRoute
  '/app/loans': typeof AppLoansRoute
  '/app/merchant': typeof AppMerchantRoute
  '/app/send': typeof AppSendRoute
  '/app/statement': typeof AppStatementRoute
  '/app/topup': typeof AppTopupRoute
  '/app/withdraw': typeof AppWithdrawRoute
  '/app/': typeof AppIndexRoute
  '/api/public/mpesa/stk-callback': typeof ApiPublicMpesaStkCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/account'
    | '/app/agent'
    | '/app/airtime'
    | '/app/lipa'
    | '/app/loans'
    | '/app/merchant'
    | '/app/send'
    | '/app/statement'
    | '/app/topup'
    | '/app/withdraw'
    | '/app/'
    | '/api/public/mpesa/stk-callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/account'
    | '/app/agent'
    | '/app/airtime'
    | '/app/lipa'
    | '/app/loans'
    | '/app/merchant'
    | '/app/send'
    | '/app/statement'
    | '/app/topup'
    | '/app/withdraw'
    | '/app'
    | '/api/public/mpesa/stk-callback'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/account'
    | '/app/agent'
    | '/app/airtime'
    | '/app/lipa'
    | '/app/loans'
    | '/app/merchant'
    | '/app/send'
    | '/app/statement'
    | '/app/topup'
    | '/app/withdraw'
    | '/app/'
    | '/api/public/mpesa/stk-callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicMpesaStkCallbackRoute: typeof ApiPublicMpesaStkCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/withdraw': {
      id: '/app/withdraw'
      path: '/withdraw'
      fullPath: '/app/withdraw'
      preLoaderRoute: typeof AppWithdrawRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/topup': {
      id: '/app/topup'
      path: '/topup'
      fullPath: '/app/topup'
      preLoaderRoute: typeof AppTopupRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/statement': {
      id: '/app/statement'
      path: '/statement'
      fullPath: '/app/statement'
      preLoaderRoute: typeof AppStatementRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/send': {
      id: '/app/send'
      path: '/send'
      fullPath: '/app/send'
      preLoaderRoute: typeof AppSendRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/merchant': {
      id: '/app/merchant'
      path: '/merchant'
      fullPath: '/app/merchant'
      preLoaderRoute: typeof AppMerchantRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/loans': {
      id: '/app/loans'
      path: '/loans'
      fullPath: '/app/loans'
      preLoaderRoute: typeof AppLoansRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/lipa': {
      id: '/app/lipa'
      path: '/lipa'
      fullPath: '/app/lipa'
      preLoaderRoute: typeof AppLipaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/airtime': {
      id: '/app/airtime'
      path: '/airtime'
      fullPath: '/app/airtime'
      preLoaderRoute: typeof AppAirtimeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agent': {
      id: '/app/agent'
      path: '/agent'
      fullPath: '/app/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/account': {
      id: '/app/account'
      path: '/account'
      fullPath: '/app/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/mpesa/stk-callback': {
      id: '/api/public/mpesa/stk-callback'
      path: '/api/public/mpesa/stk-callback'
      fullPath: '/api/public/mpesa/stk-callback'
      preLoaderRoute: typeof ApiPublicMpesaStkCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAgentRoute: typeof AppAgentRoute
  AppAirtimeRoute: typeof AppAirtimeRoute
  AppLipaRoute: typeof AppLipaRoute
  AppLoansRoute: typeof AppLoansRoute
  AppMerchantRoute: typeof AppMerchantRoute
  AppSendRoute: typeof AppSendRoute
  AppStatementRoute: typeof AppStatementRoute
  AppTopupRoute: typeof AppTopupRoute
  AppWithdrawRoute: typeof AppWithdrawRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAgentRoute: AppAgentRoute,
  AppAirtimeRoute: AppAirtimeRoute,
  AppLipaRoute: AppLipaRoute,
  AppLoansRoute: AppLoansRoute,
  AppMerchantRoute: AppMerchantRoute,
  AppSendRoute: AppSendRoute,
  AppStatementRoute: AppStatementRoute,
  AppTopupRoute: AppTopupRoute,
  AppWithdrawRoute: AppWithdrawRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicMpesaStkCallbackRoute: ApiPublicMpesaStkCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
